apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deploy
  namespace: todos
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: todo-api
  template:
    metadata:
      name: todo-api-pod
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api-container
          image: todos-todo:v1
          ports: 
           - containerPort: 5002
          env:
           - name: USERS_API_URL
             valueFrom:
               configMapKeyRef:
                 name: env-cm
                 key: users
           - name: AUTH_API_URL
             valueFrom:
               configMapKeyRef:
                 name: env-cm
                 key: auth
---
apiVersion: v1
kind: Service
metadata:
  name: todo-svc
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 31133
