apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deploy
  namespace: todos
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: users-api
  template:
    metadata:
      name: users-api-pod
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api-container
          image: todos-users:v1
          ports: 
           - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 31131
